package com.digital.commonlibrary.enums;

public enum ErrorCode {
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    RESOURCE_NOT_FOUND,
    MALFORMED_JSON,
    PURCHASER_ORDER_NOT_FOUND,
    SHOPKEEPER_NOT_FOUND,
    LOCATION_NOT_FOUND,
    SHOPKEEPER_LOCATION_NOT_EXIST,
    SHOPKEEPER_LOCATION_MENU_ITEM_NOT_EXIST,
    SHOPKEEPER_FEIGN_CLIENT_ERROR
}
